import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import Providers from "./providers";
import Header from "./_components/header";
import { ClerkProvider, currentUser } from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await currentUser()

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable}`}>
          <Providers>
            <TRPCReactProvider headers={headers()}>
              { user && <Header /> }
              {children}
            </TRPCReactProvider>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
